modkit = modkit or {};
if (modkit.ship_types == nil) then

	if (modkit.table == nil) then
		dofilepath("data:scripts/modkit/table_util.lua");
	end

	-- generated by `modkit-tools/ship-types.js`
	---@enum ShipType
	modkit.ship_types = {};
end
