modkit = modkit or {};
if (modkit.ship_types == nil) then

	if (modkit.table == nil) then
		dofilepath("data:scripts/modkit/table_util.lua");
	end

	-- generated by `modkit-tools/ship-types.js`
	---@enum ShipType
	modkit.ship_types = {};

	for _, type in { 'horde_manager', 'horde_shipyard' } do
		modkit.table.push(modkit.ship_types, type);
	end
end
