if (MK_SHIP_TYPES == nil) then

	if (modkit == nil) then
		dofilepath("data:scripts/modkit/table_util.lua");
	end

	-- generated by `modkit-tools/ship-types.js`
	modkit.ship_types = {};

	MK_SHIP_TYPES = 1;
end
